### ISSUE TITLE
prometheus配置kvass sidecar后总会第一次挂掉

### ISSUE THREAD

**Issue by like-inspur** [tkestack/kvass#21]
我部署配置了kvass sidecar的prometheus，发现Pod总会重启一次，查看日志发现kvaas sidecar启动后连接prometheus的url，因为连接不上导致程序挂掉，这里能否在连接时增加从重试逻辑，避免第一次启动时总是显示重启次数为1

root@mgt01:~# kubectl get pod|grep prometheus
prometheus-0                                       3/3     Running   1          37m
prometheus-1                                       3/3     Running   1          30m
prometheus-2                                       3/3     Running   1          30m

root@mgt01:~# kubectl logs prometheus-0 kvass -p
time="2021-02-18T07:45:21Z" level=info msg="config inject completed" component=injector
panic: apply config: Post "http://127.0.0.1:9090/-/reload": dial tcp 127.0.0.1:9090: connect: connection refused

goroutine 1 [running]:
main.glob..func2(0x3b39100, 0x3b82c70, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/kvass/kvass/cmd/kvass/sidecar.go:109 +0xbae
github.com/spf13/cobra.(*Command).execute(0x3b39100, 0x3b82c70, 0x0, 0x0, 0x3b39100, 0x3b82c70)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x3b38e60, 0x1664c7ddbad24102, 0x3b50180, 0x0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/kvass/kvass/cmd/kvass/main.go:42 +0x11c

**Comment by RayHuangCN** [comment]
这里是因为容器之间有一定启动顺序要求导致的，使用容器的重启逻辑也是社区典型的做法哦。

**Comment by like-inspur** [comment]
是不是加个重试逻辑比较好，相当于可以等待prometheus起来

**Comment by RayHuangCN** [comment]
这里确实是个问题，我们在下个版本改进一下这里

**Comment by like-inspur** [comment]
好的
